### ISSUE TITLE
collaboration avec Apereo

### ISSUE THREAD

**Issue by ChristianMurphy** [EsupPortail/ProlongationENT-alerts#1]
Bonjour
J'ai remarqué que cet excellent composant recoupe en partie les capacités du portlet de notification uPortal.
Le portlet de notification contient des [composants Web](https://developer.mozilla.org/fr/docs/Web/Web_Components) (Web Components) pouvant être inclus dans des pages extérieures à uPortal.
comprenant:
`notification-banner`
![screenshot_2019-02-22 notification-banner](https://user-images.githubusercontent.com/3107513/53258781-ba454780-368a-11e9-8fec-4187e08070c5.png)
https://github.com/Jasig/NotificationPortlet/tree/master/notification-portlet-webcomponents/notification-banner

`notification-icon`
![screenshot_2019-02-22_10-16-48](https://user-images.githubusercontent.com/3107513/53258942-190ac100-368b-11e9-85c6-542a6eaba987.png)
https://github.com/Jasig/NotificationPortlet/tree/master/notification-portlet-webcomponents/notification-icon

`notification-modal`
![screenshot_2019-02-22 notification-modal](https://user-images.githubusercontent.com/3107513/53259017-45bed880-368b-11e9-8770-9e6218b0534b.png)
https://github.com/Jasig/NotificationPortlet/tree/master/notification-portlet-webcomponents/notification-modal

nous pouvons collaborer avec ces composants Web pour offrir aux étudiants une meilleure expérience utilisateur.

**Comment by prigaux** [comment]
Hi,

This project is really small and we have a lot of different technological choices which makes it hard to share: ProlongationENT is used on many different and sometimes weird applications, that's why - when possible - we use iframes to have a complete autonomy (much easier than web components).

One interesting level of sharing would be a Vue.js component which would take information to use as parameters. But still too small for this project I would say.

cu
